"@protocol= http",
"@domainname= localhost",
"@port= {{dotenv PORT}}",
"@path=v1",
"@baseUrl = {{protocol}}://{{domainname}}:{{port}}/{{path}}"

### Route GET /boardgames

GET http://localhost:3000/v1/boardgames

### Route GET /boardgames/{id}

GET http://localhost:3000/v1/boardgames/4


### Ajout d'un jeu avec id

POST http://localhost:3000/v1/boardgames
Content-Type: application/json

{
    "name": "Dixit",
    "min_age": 8,
    "min_players": 3,
    "max_players": 6,
    "type" : "familial",
    "note" : 5,
    "duration" : "30 minutes",
    "creator" : "Jean-Louis Roubira"
}


### Suppression d'un jeu

DELETE {{baseUrl}}/boardgames

### Modification d'un jeu

UPDATE {{baseUrl}}/boardgames