@protocol= http
@domainname= localhost
@port= {{$dotenv PORT}}
@path=v1
@baseUrl = {{protocol}}://{{domainname}}:{{port}}/{{path}}


### Route GET /boardgames

GET {{baseUrl}}/boardgames


### Route GET /boardgames/{id}

GET {{baseUrl}}/boardgames/1


### Ajout d'un jeu avec id

POST {{baseUrl}}/boardgames
Content-Type: application/json

{
    "name": "Dixit",
    "minAge": 8,
    "minPlayers": 3,
    "maxPlayers": 6,
    "type" : "familial",
    "note" : 5,
    "duration" : 30,
    "creator" : "Jean-Louis Roubira"
}


### Suppression d'un jeu

DELETE {{baseUrl}}/boardgames/1


### Modification d'un jeu

PATCH {{baseUrl}}/boardgames/4
Content-Type: application/json

{
    "name": "Dixit",
    "minAge": 8,
    "minPlayers": 3,
    "maxPlayers": 6,
    "type" : "familial",
    "note" : 5,
    "duration" : 30,
    "creator" : "Jean-Louis Roubira"
}